### ISSUE TITLE
Fails to start on 5.4

### ISSUE THREAD

**Issue by Taffer** [moussetc/mattermost-plugin-emoticon2emoji#2]
This one fails to start on Mattermost 5.4:

`{"level":"error","ts":1542655298.7106464,"caller":"app/plugin.go:70","msg":"Unable to activate plugin","plugin_id":"com.github.moussetc.mattermost.plugin.emoticon2emoji","error":"unable to start plugin: com.github.moussetc.mattermost.plugin.emoticon2emoji: plugin exited before we could connect","errorVerbose":"plugin exited before we could connect\nunable to start plugin: com.github.moussetc.mattermost.plugin.emoticon2emoji\ngithub.com/mattermost/mattermost-server/plugin.(*Environment).Activate\n\t/home/ubuntu/jenkins/workspace/msr/mattermost-platform-release/src/github.com/mattermost/mattermost-server/plugin/environment.go:211\ngithub.com/mattermost/mattermost-server/app.(*App).SyncPluginsActiveState\n\t/home/ubuntu/jenkins/workspace/msr/mattermost-platform-release/src/github.com/mattermost/mattermost-server/app/plugin.go:68\ngithub.com/mattermost/mattermost-server/app.(*App).InitPlugins.func2\n\t/home/ubuntu/jenkins/workspace/msr/mattermost-platform-release/src/github.com/mattermost/mattermost-server/app/plugin.go:141\ngithub.com/mattermost/mattermost-server/app.(*App).InvokeConfigListeners\n\t/home/ubuntu/jenkins/workspace/msr/mattermost-platform-release/src/github.com/mattermost/mattermost-server/app/config.go:138\ngithub.com/mattermost/mattermost-server/app.(*App).UpdateConfig\n\t/home/ubuntu/jenkins/workspace/msr/mattermost-platform-release/src/github.com/mattermost/mattermost-server/app/config.go:50\ngithub.com/mattermost/mattermost-server/app.(*App).EnablePlugin\n\t/home/ubuntu/jenkins/workspace/msr/mattermost-platform-release/src/github.com/mattermost/mattermost-server/app/plugin.go:206\ngithub.com/mattermost/mattermost-server/api4.enablePlugin\n\t/home/ubuntu/jenkins/workspace/msr/mattermost-platform-release/src/github.com/mattermost/mattermost-server/api4/plugin.go:183\ngithub.com/mattermost/mattermost-server/web.Handler.ServeHTTP\n\t/home/ubuntu/jenkins/workspace/msr/mattermost-platform-release/src/github.com/mattermost/mattermost-server/web/handlers.go:131\ngithub.com/mattermost/mattermost-server/web.(*Handler).ServeHTTP\n\t<autogenerated>:1\ngithub.com/mattermost/mattermost-server/vendor/github.com/gorilla/mux.(*Router).ServeHTTP\n\t/home/ubuntu/jenkins/workspace/msr/mattermost-platform-release/src/github.com/mattermost/mattermost-server/vendor/github.com/gorilla/mux/mux.go:162\ngithub.com/mattermost/mattermost-server/vendor/github.com/gorilla/handlers.recoveryHandler.ServeHTTP\n\t/home/ubuntu/jenkins/workspace/msr/mattermost-platform-release/src/github.com/mattermost/mattermost-server/vendor/github.com/gorilla/handlers/recovery.go:78\ngithub.com/mattermost/mattermost-server/vendor/github.com/gorilla/handlers.(*recoveryHandler).ServeHTTP\n\t<autogenerated>:1\nnet/http.serverHandler.ServeHTTP\n\t/usr/local/go/src/net/http/server.go:2741\nnet/http.(*conn).serve\n\t/usr/local/go/src/net/http/server.go:1847\nruntime.goexit\n\t/usr/local/go/src/runtime/asm_amd64.s:1333"}`

**Comment by Taffer** [comment]
Doesn't compile either:

```
$ make
go test -race -coverprofile=coverage.txt -covermode=atomic
plugin.go:9:2: cannot find package "github.com/mattermost/mattermost-server/plugin/rpcplugin" in any of:
        /usr/lib/go-1.10/src/github.com/mattermost/mattermost-server/plugin/rpcplugin (from $GOROOT)
        /home/chrish/go/src/github.com/mattermost/mattermost-server/plugin/rpcplugin (from $GOPATH)
Makefile:39: recipe for target 'test-coverage' failed
make: *** [test-coverage] Error 1
```

Looks like the code needs to be upgraded for APIv4?

**Comment by moussetc** [comment]
Yes, the code needs to be updated for the breaking changes introduced in 5.2. But as there will also be breaking changes in future 5.6, I might as well do those as well, even if it takes a bit longer.

(As a side-note, do you plan on using this plugin? I did it more as a test of the message previewing API than with a serious use in mind, so I'm curious.)

**Comment by Taffer** [comment]
I just noticed it today; someone pointed out your `/spoiler` plugin so I looked at your other repos. ;-)

https://github.com/mattermost/mattermost-plugin-autolink can do it too, I'll just have to enter the patterns by hand.

Cheers!
